//自定义的头文件
#ifndef YYTAB_H
#define YYTAB_H
#define BREAK       0
#define CASE        1
#define CHAR        2
#define CONST       3
#define CONTINUE    4
#define DEFAULT     5
#define DO          6
#define DOUBLE      7
#define ELSE        8
#define ENUM        9
#define FLOAT      10
#define FOR        11
#define GOTO       12
#define IF         13
#define INT        14
#define LONG       15
#define RETURN     16
#define SHORT      17
#define SIGNED     18
#define SIZEOF     19
#define STATIC     20
#define SWITCH     21
#define TYPEDEF    22
#define UNSIGNED   23
#define VOID       24
#define WHILE      25
#define IDENTIFIER 26 
#define NUMBER     27
#define ADD_ASSIGN 28
#define SUB_ASSIGN 29
#define MUL_ASSIGN 30
#define DIV_ASSIGN 31
#define INC_OP     32
#define DEC_OP     33
#define PTR_OP     34
#define AND_OP     35
#define OR_OP      36
#define LE_OP      37
#define GE_OP      38
#define EQ_OP      39
#define NE_OP      40 
#define E_OP       41
#define L_OP       42
#define G_OP       43
#define SEMICOLON  44
#define COMMA      45
#define COLON      46
#define POINT      47
#define AND        48
#define EXCLAMATION  49 
#define DEC        50			
#define INC        51
#define SATR       52
#define OR         53
#define UNKNOWN    54
#define L_BRACKETS 55
#define R_BRACKETS 56
#define SL_BRACKETS 57
#define RL_BRACKETS 58
#define ERROR      32767
#endif